# Generated by Django 4.1.7 on 2023-03-12 17:46

import bowser_web.users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", bowser_web.users.models.UserManager()),
            ],
        ),
    ]
